/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005236",
        "tertiary": "#693d00",
        "on-primary-fixed": "#002114",
        "background": "#f8f9fa",
        "outline-variant": "#bfc9c1",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#85d7ad",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f0f1f2",
        "inverse-surface": "#2e3132",
        "tertiary-container": "#8a5200",
        "on-background": "#191c1d",
        "outline": "#707973",
        "on-error": "#ffffff",
        "surface": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-tertiary-fixed-variant": "#683d00",
        "primary-fixed": "#b1f0ce",
        "secondary": "#0e6c4a",
        "surface-tint": "#2c694e",
        "inverse-primary": "#95d4b3",
        "surface-container-low": "#f3f4f5",
        "primary-container": "#2d6a4f",
        "tertiary-fixed-dim": "#ffb86b",
        "surface-dim": "#d9dadb",
        "on-primary-fixed-variant": "#0e5138",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffd1a5",
        "on-secondary-fixed": "#002113",
        "tertiary-fixed": "#ffdcbc",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#404943",
        "primary": "#0f5238",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed-dim": "#95d4b3",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#2c1700",
        "on-primary-container": "#a8e7c5",
        "secondary-fixed": "#a0f4c8",
        "on-secondary-container": "#19724f",
        "surface-bright": "#f8f9fa",
        "on-surface": "#191c1d",
        "secondary-container": "#a0f4c8",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "20px",
        base: "8px",
        lg: "32px",
        "margin-page": "20px",
        gutter: "14px",
        sm: "10px",
        xs: "4px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-total-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "display-total": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
